import Container from "app/components/Container";

export default async function PrivacyPolicyPage() {
	return (
		<Container>
			<strong>Welcome to Slyderz, LLC.</strong>
			<br />
			<p>
				Slyderz, LLC. (“us”, “we”, or “our”) operates https://slyderz.com
				(hereinafter referred to as “Service”).
			</p>
			<br />
			<p>
				Our Privacy Policy governs your visit to https://slyderz.com, and
				explains how we collect, safeguard and disclose information that results
				from your use of our Service.
			</p>
			<br />
			<p>
				By using Service, you agree to the collection and use of information in
				accordance with this policy. Unless otherwise defined in this Privacy
				Policy, the terms used in this Privacy Policy have the same meanings as
				in our Terms and Conditions.
			</p>
			<br />
			<p>Definitions</p>

			<p>
				<strong>Service</strong> means the https://slyderz.com website operated
				by Slyderz, LLC.
			</p>
			<br />
			<p>
				<strong>Personal Data</strong> means data about a living individual who
				can be identified from those data (or from those and other information
				either in our possession or likely to come into our possession).
			</p>
			<br />
			<p>
				<strong>Usage Data</strong> is data collected automatically either
				generated by the use of Service or from Service infrastructure itself
				(for example, the duration of a page visit).
			</p>
			<br />
			<p>
				<strong>Cookies</strong> are small files stored on your device (computer
				or mobile device).
			</p>
			<br />
			<p>
				<strong>Data Controller</strong> means a natural or legal person who
				(either alone or jointly or in common with other persons) determines the
				purposes for which and the manner in which any personal data are, or are
				to be, processed. For the purpose of this Privacy Policy, we are a Data
				Controller of your data.
			</p>
			<br />
			<p>
				<strong>Data Processors (on service providers)</strong> means any
				natural or legal person who processes the data on behalf of the Data
				Controller. We may use the services of various Service Providers in
				order to process your data more effectively.
			</p>
			<br />
			<p>
				<strong>Data Subject</strong> is any living individual who is the
				subject of Personal Data.
			</p>
			<br />
			<p>
				<strong>The User</strong> is the individual using our Service. The User
				corresponds to the Data Subject, who is the subject of Personal Data.
			</p>
			<br />
			<strong>Information Collection and Use</strong>
			<br />
			<p>
				We collect several different types of information for various purposes
				to provide and improve our Service to you.
			</p>
			<br />
			<strong>Types of Data Collected</strong>
			<br />
			<p>Personal Data</p>
			<br />
			<p>
				While using our Service, we may ask you to provide us with certain
				personally identifiable information that can be used to contact or
				identify you (“Personal Data”). Personally identifiable information may
				include, but is not limited to:
			</p>
			<br />
			<ul>
				<li>Email address</li>
				<li>First name and last name</li>
				<li>Cookies and Usage Data</li>
			</ul>
			<br />
			<p>
				We may use your Personal Data to contact you with newsletters, marketing
				or promotional materials and other information that may be of interest
				to you. You may opt out of receiving any, or all, of these
				communications from us by following the unsubscribe link or by emailing
				us at support@slyderz.com.
			</p>
			<br />
			<p>
				We may also collect information that your browser sends whenever you
				visit our Service or when you access Service by or through a mobile
				device (“Usage Data”).
			</p>
			<br />
			<p>
				This Usage Data may include information such as your computer&apos;s
				Internet Protocol address (e.g. IP address), browser type, browser
				version, the pages of our Service that you visit, the time and date of
				your visit, the time spent on those pages, unique device identifiers and
				other diagnostic data.
			</p>
			<br />
			<p>
				When you access Service with a mobile device, this Usage Data may
				include information such as the type of mobile device you use, your
				mobile device unique ID, the IP address of your mobile device, your
				mobile operating system, the type of mobile Internet browser you use,
				unique device identifiers and other diagnostic data.
			</p>
			<br />
			<p>
				We use cookies and similar tracking technologies to track the activity
				on our Service and we hold certain information.
			</p>
			<br />
			<p>
				Cookies are files with a small amount of data which may include an
				anonymous unique identifier. Cookies are sent to your browser from a
				website and stored on your device. Other tracking technologies are also
				used such as beacons, tags and scripts to collect and track information
				and to improve and analyze our Service.
			</p>
			<br />
			<p>
				You can instruct your browser to refuse all cookies or to indicate when
				a cookie is being sent. However, if you do not accept cookies, you may
				not be able to use some portions of our Service.
			</p>
			<br />
			<strong>Examples of Cookies we use:</strong>
			<br />
			<ul>
				<li>Session Cookies: We use Session Cookies to operate our Service.</li>
				<li>
					Preference Cookies: We use Preference Cookies to remember your
					preferences and various settings.
				</li>
				<li>
					Security Cookies: We use Security Cookies for security purposes.
				</li>
				<li>
					Advertising Cookies: Advertising Cookies are used to serve you with
					advertisements that may be relevant to you and your interests.
				</li>
			</ul>
			<br />
			<strong>Use of Data</strong>
			<br />
			<p>Slyderz, LLC. uses the collected data for various purposes:</p>
			<br />
			<p>
				<strong>Personal Data</strong>
			</p>
			<br />
			<p>- to provide and maintain our Service;</p>
			<br />
			<p>- to notify you about changes to our Service;</p>
			<br />
			<p>
				- to allow you to participate in interactive features of our Service
				when you choose to do so;
			</p>
			<br />
			<p>- to provide customer support;</p>
			<br />
			<p>
				- to gather analysis or valuable information so that we can improve our
				Service;
			</p>
			<br />
			<p>- to monitor the usage of our Service;</p>
			<br />
			<p>- to detect, prevent and address technical issues;</p>
			<br />
			<p>- to fulfill any other purpose for which you provide it;</p>
			<br />
			<p>
				- to carry out our obligations and enforce our rights arising from any
				contracts entered into between you and us, including for billing and
				collection;
			</p>
			<br />
			<p>
				- to provide you with notices about your account and/or subscription,
				including expiration and renewal notices, email-instructions, etc.;
			</p>
			<br />
			<p>
				- to provide you with news, special offers and general information about
				other goods, services and events which we offer that are similar to
				those that you have already purchased or enquired about unless you have
				opted not to receive such information;
			</p>
			<br />
			<p>
				- in any other way we may describe when you provide the information;
			</p>
			<br />
			<p>- for any other purpose with your consent.</p>
			<br />
			<strong>Retention of Data</strong>
			<br />
			<p>
				We will retain your Personal Data only for as long as is necessary for
				the purposes set out in this Privacy Policy. We will retain and use your
				Personal Data to the extent necessary to comply with our legal
				obligations (for example, if we are required to retain your data to
				comply with applicable laws), resolve disputes, and enforce our legal
				agreements and policies.
			</p>
			<br />
			<p>
				We will also retain Usage Data for internal analysis purposes. Usage
				Data is generally retained for a shorter period, except when this data
				is used to strengthen the security or to improve the functionality of
				our Service, or we are legally obligated to retain this data for longer
				time periods.
			</p>
			<br />
			<strong>Transfer of Data</strong>
			<br />
			<p>
				Your information, including Personal Data, may be transferred to – and
				maintained on – computers located outside of your state, province,
				country or other governmental jurisdiction where the data protection
				laws may differ from those of your jurisdiction.
			</p>
			<br />
			<p>
				If you are located outside United States and choose to provide
				information to us, please note that we transfer the data, including
				Personal Data, to United States and process it there.
			</p>
			<br />
			<p>
				Your consent to this Privacy Policy followed by your submission of such
				information represents your agreement to that transfer.
			</p>
			<br />
			<p>
				Slyderz, LLC. will take all the steps reasonably necessary to ensure
				that your data is treated securely and in accordance with this Privacy
				Policy and no transfer of your Personal Data will take place to an
				organisation or a country unless there are adequate controls in place
				including the security of your data and other personal information.
			</p>
			<br />
			<strong>Disclosure of Data</strong>
			<br />
			<p>
				We may disclose personal information that we collect, or you provide:
			</p>
			<br />
			<p>
				<strong>Disclosure for Law Enforcement.</strong>
			</p>
			<br />
			<p>
				Under certain circumstances, we may be required to disclose your
				Personal Data if required to do so by law or in response to valid
				requests by public authorities.
			</p>
			<br />
			<p>
				<strong>Business Transaction.</strong>
			</p>
			<br />
			<p>
				If we or our subsidiaries are involved in a merger, acquisition or asset
				sale, your Personal Data may be transferred.
			</p>
			<br />
			<p>
				<strong>Other cases.</strong> We may disclose your information also:
			</p>
			<br />
			<p>- to fulfill the purpose for which you provide it;</p>
			<br />
			<p>- for the purpose of including your company’s logo on our website;</p>
			<br />
			<p>- for any other purpose with your consent.</p>
			<br />
			<p>Security of Data</p>
			<br />
			<p>
				The security of your data is important to us but remember that no method
				of transmission over the Internet or method of electronic storage is
				100% secure. While we strive to use commercially acceptable means to
				protect your Personal Data, we cannot guarantee its absolute security.
			</p>
			<br />
			<p>
				Your Data Protection Rights Under General Data Protection Regulation
				(GDPR)
			</p>
			<br />
			<p>
				If you are a resident of the European Union (EU) and European Economic
				Area (EEA), you have certain data protection rights, covered by GDPR.
			</p>
			<br />
			<p>
				- <strong>The right to access</strong>, update or to delete the
				information we have on you;
			</p>
			<br />
			<p>
				- <strong>The right of rectification.</strong> You have the right to
				have your information rectified if that information is inaccurate or
				incomplete;
			</p>
			<br />
			<p>
				- <strong>The right to object.</strong> You have the right to object to
				our processing of your Personal Data;
			</p>
			<br />
			<p>
				- <strong>The right of restriction.</strong> You have the right to
				request that we restrict the processing of your personal information;
			</p>
			<br />
			<p>
				- <strong>The right to data portability.</strong> You have the right to
				be provided with a copy of your Personal Data in a structured,
				machine-readable and commonly used format;
			</p>
			<br />
			<p>
				- <strong>The right to withdraw consent.</strong> You also have the
				right to withdraw your consent at any time where we rely on your consent
				to process your personal information;
			</p>
			<br />
			<p>
				Please note that we may ask you to verify your identity before
				responding to such requests. Please note, we may not able to provide
				Service without some necessary data.
			</p>
			<br />
			<p>
				You have the right to complain to a Data Protection Authority about our
				collection and use of your Personal Data. For more information, please
				contact your local data protection authority in the European Economic
				Area (EEA).
			</p>
			<br />
			<p>
				Your Data Protection Rights under the California Privacy Protection Act
				(CalOPPA)
			</p>

			<p>
				CalOPPA is the first state law in the nation to require commercial
				websites and online services to post a privacy policy. The law’s reach
				stretches well beyond California to require a person or company in the
				United States (and conceivable the world) that operates websites
				collecting personally identifiable information from California consumers
				to post a conspicuous privacy policy on its website stating exactly the
				information being collected and those individuals with whom it is being
				shared, and to comply with this policy.
			</p>
			<br />
			<p>According to CalOPPA we agree to the following:</p>
			<br />
			<p>- users can visit our site anonymously;</p>
			<br />
			<p>
				- our Privacy Policy link includes the word “Privacy”, and can easily be
				found on the page specified above on the home page of our website;
			</p>
			<br />
			<p>
				- users will be notified of any privacy policy changes on our Privacy
				Policy Page;
			</p>
			<br />
			<p>
				- users are able to change their personal information by emailing us at
				support@slyderz.com.
			</p>
			<br />
			<strong>Our Policy on “Do Not Track” Signals:</strong>
			<br />
			<p>According to CalOPPA we agree to the following:</p>
			<br />
			<p>
				We honor Do Not Track signals and do not track, plant cookies, or use
				advertising when a Do Not Track browser mechanism is in place. Do Not
				Track is a preference you can set in your web browser to inform websites
				that you do not want to be tracked.
			</p>
			<br />
			<p>
				You can enable or disable Do Not Track by visiting the Preferences or
				Settings page of your web browser.
			</p>
			<br />
			<strong>Service Providers</strong>
			<br />
			<p>
				We may employ third party companies and individuals to facilitate our
				Service (“Service Providers”), provide Service on our behalf, perform
				Service-related services or assist us in analysing how our Service is
				used.
			</p>
			<br />
			<p>
				These third parties have access to your Personal Data only to perform
				these tasks on our behalf and are obligated not to disclose or use it
				for any other purpose.
			</p>
			<br />
			<strong>Analytics</strong>
			<br />
			<p>
				We may use third-party Service Providers to monitor and analyze the use
				of our Service.
			</p>
			<br />
			<p>
				- <strong>Google Analytics</strong> is a web analytics service offered
				by Google that tracks and reports website traffic. Google uses the data
				collected to track and monitor the use of our Service. This data is
				shared with other Google services. Google may use the collected data to
				contextualize and personalize the ads of its own advertising network.
				You can opt-out of having made your activity on the Service available to
				Google Analytics by installing the Google Analytics opt-out browser
				add-on. The add-on prevents the Google Analytics JavaScript (ga.js,
				analytics.js and dc.js) from sharing information with Google Analytics
				about visits activity. For more information on the privacy practices of
				Google, please visit the Google Privacy & Terms web page:
				https://policies.google.com/privacy?hl=en
			</p>
			<br />
			<strong>Email Marketing</strong>
			<br />
			<p>
				We may use your Personal Data to contact you with newsletters, marketing
				or promotional materials and other information that may be of interest
				to you. You may opt out of receiving any, or all, of these
				communications from us by following the unsubscribe link or by emailing
				us at support@slyderz.com.
			</p>
			<br />
			<strong>Links to Other Sites</strong>
			<br />
			<p>
				Our Service may contain links to other sites that are not operated by
				us. If you click a third party link, you will be directed to that third
				party&apos;s site. We strongly advise you to review the Privacy Policy
				of every site you visit.
			</p>
			<br />
			<p>
				We have no control over and assume no responsibility for the content,
				privacy policies or practices of any third party sites or services.
			</p>
			<br />
			<p>Children&apos;s Privacy</p>
			<br />
			<p>
				Our Service does not address anyone under the age of 18 (“Children”).
			</p>
			<br />
			<p>
				We do not knowingly collect personally identifiable information from
				anyone under the age of 18. If you are a parent or guardian and you are
				aware that your Child has provided us with Personal Data, please contact
				us. If we become aware that we have collected Personal Data from
				children without verification of parental consent, we take steps to
				remove that information from our servers.
			</p>
			<br />
			<p>
				If we need to rely on consent as a legal basis for processing your
				information and your country requires consent from a parent, we may
				require your parent&apos;s consent before we collect and use that
				information.
			</p>
			<br />
			<strong>Changes to This Privacy Policy</strong>
			<br />
			<p>
				We may update our Privacy Policy from time to time. We will notify you
				of any changes by posting the new Privacy Policy on this page. We will
				let you know via email and/or a prominent notice on our Service, prior
				to the change becoming effective and update the “effective date” at the
				top of this Privacy Policy. You are advised to review this Privacy
				Policy periodically for any changes. Changes to this Privacy Policy are
				effective when they are posted on this page.
			</p>
			<br />
			<strong>Contact Us</strong>
			<br />
			<p>
				If you have any questions about this Privacy Policy, please contact us
				by email: support@slyderz.com.
			</p>
		</Container>
	);
}
