name: Deploy to Railway
description: Deploy to Railway
inputs:
  RAILWAY_SERVICE_ID:
    description: 'Railway service ID'
    required: true
  RAILWAY_TOKEN:
    description: 'Railway token'
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v2

    - run: bash <(curl -fsSL cli.new)
      shell: bash

    - run: railway up --service ${{ inputs.RAILWAY_SERVICE_ID }}
      shell: bash
      env:
        RAILWAY_TOKEN: ${{ inputs.RAILWAY_TOKEN }}
