name: Build Slyderz
on:
  workflow_call:
    secrets:
      DATABASE_URL:
        required: true
      NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME:
        required: true
      SECRET_COOKIE_PASSWORD:
        required: true
      STRIPE_SECRET_KEY:
        required: true
      STRIPE_ENDPOINT_SECRET:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      CLOUDINARY_API_KEY:
        required: true
      MJ_APIKEY_PRIVATE:
        required: true
      MJ_APIKEY_PUBLIC:
        required: true
      CAPTCHA_SECRET:
        required: true
      NEXT_PUBLIC_CAPTCHA_SITEKEY:
        required: true
      CONTENTFUL_TOKEN:
        required: true
      CONTENTFUL_ACCESS_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: "staging"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node 20
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: pnpm

      - name: Install packages
        run: pnpm install

      - name: Building Slyderz
        env:
          NEXT_PUBLIC_URL: "http://localhost:3000"
          NEXT_PUBLIC_CAPTCHA_SITEKEY: ${{ secrets.NEXT_PUBLIC_CAPTCHA_SITEKEY}}
          NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: ${{ secrets.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME}}
          DATABASE_URL: ${{ secrets.DATABASE_URL}}
          SECRET_COOKIE_PASSWORD: ${{ secrets.SECRET_COOKIE_PASSWORD}}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY}}
          STRIPE_ENDPOINT_SECRET: ${{ secrets.STRIPE_ENDPOINT_SECRET}}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY}}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET}}
          MJ_APIKEY_PRIVATE: ${{ secrets.MJ_APIKEY_PRIVATE}}
          MJ_APIKEY_PUBLIC: ${{ secrets.MJ_APIKEY_PUBLIC}}
          CAPTCHA_SECRET: ${{ secrets.CAPTCHA_SECRET}}
          CONTENTFUL_TOKEN: ${{ secrets.CONTENTFUL_TOKEN}}
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN}}
        run: pnpm run build

      - name: Upload Next build
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            .next
            public
          retention-days: 7
