name: Deploy Slyderz
on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node 18
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Building Slyderz
        run: yarn run build

  if_merged:
    needs: [build]
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: everlytic/branch-merge@1.1.2
        with:
          github_token: ${{ github.token }}
          source_ref: ${{ github.ref }}
          target_branch: 'main'
          commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'
    # steps:
    #   - run: echo deploying staging
    #   - name: Deploy to staging
#       - name: Install Railway
#         run: npm i -g @railway/cli

#       - name: Deploy Slyderz
#         run: railway up
#         env:
#           RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
