name: Deploy main to staging
on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    concurrency: staging

  if_merged:
    needs: [build]
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Deploy to staging
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
