name: Merge to main
on:
  pull_request:
    types:
      - opened
    branches:
      - main

concurrency: staging
jobs:
  build_staging:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/build.yml
    secrets: inherit
