name: Deploy main to staging
on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  deploy_staging:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  if_merged:
    needs: [deploy_staging]
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    concurrency: staging
    environment: staging
    permissions:
      pull-requests: read
    name: Merge into staging and deploy
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create PR main -> staging
        run: gh pr create -B staging -H main --title 'Merge main into staging' --body 'Created by Github action'
        id: createPR
        env:
          PR_NUMBER: ${{ github.event.number }}

      - name: Merge PR main -> staging
        run: gh pr merge ${{ steps.createPR.outputs.PR_NUMBER }} --auto -d -s

      - name: Install Railway
        run: bash <(curl -fsSL cli.new)

      - name: Deploy to staging
        run: railway up --service ${{ secrets.RAILWAY_SERVICE_ID }}
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
