name: Deploy main to staging
on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  # build_staging:
  #   uses: ./.github/workflows/build.yml
  #   secrets: inherit

  if_merged:
    # needs: [build_staging]
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    concurrency: staging
    environment: staging
    name: Deploy to staging
    steps:
      - uses: chrnorm/deployment-action@v2
        name: Create GitHub deployment
        id: deployment
        with:
          token: "${{ github.token }}"
          environment-url: https://staging.slyderz.co
          environment: staging

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Railway
        run: bash <(curl -fsSL cli.new)

      - name: Deploy to Railway
        run: railway up --service ${{ secrets.RAILWAY_SERVICE_ID }}
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@v2
        with:
          token: "${{ github.token }}"
          environment-url: ${{ steps.deployment.outputs.environment_url }}
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          state: "success"

      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@v2
        with:
          token: "${{ github.token }}"
          environment-url: ${{ steps.deployment.outputs.environment_url }}
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          state: "failure"
