name: Deploy main to staging
on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  # deploy_staging:
  #   uses: ./.github/workflows/build.yml
  #   secrets: inherit

  if_merged:
    # needs: [deploy_staging]
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    concurrency: staging
    environment: staging
    name: Merge into staging and deploy
    env:
      GH_TOKEN: ${{ github.token }}
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create PR main -> staging
        run: |
          gh pr create -B staging -H main --title 'Merge main into staging' --body 'Created by Github action'
          echo "::set-output name=pull_request_number::$(gh pr view --json number -q .number || echo "")"
        id: createPR

      - name: Merge PR main -> staging
        run: gh pr merge ${{ steps.createPR.outputs.pull_request_number }} --auto -d -s

      - name: Install Railway
        run: bash <(curl -fsSL cli.new)

      - name: Deploy to staging
        run: railway up --service ${{ secrets.RAILWAY_SERVICE_ID }}
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
