name: Merge feature branch into main
on:
  push:
    branches:
      - main

concurrency: staging
jobs:
  build_staging:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  deploy_staging:
    needs: [build_staging]
    runs-on: ubuntu-latest
    environment: staging
    name: Deploy to staging
    steps:
      - name: Checkout
        uses: actions/checkout@v3
