name: Deploy to production
on:
  pull_request:
    branches:
      - production

jobs:
  # build_production:
  #   uses: ./.github/workflows/build.yml
  #   secrets: inherit

  deploy_to_production:
    # needs: [build_production]
    runs-on: ubuntu-latest
    environment: production
    name: Deploy to production
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: chrnorm/deployment-action@v2
        name: Create GitHub deployment
        id: deployment
        with:
          token: "${{ github.token }}"
          environment-url: https://slyderz.co
          environment: production

      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@v2
        with:
          token: "${{ github.token }}"
          environment-url: ${{ steps.deployment.outputs.environment_url }}
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          state: "success"

      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@v2
        with:
          token: "${{ github.token }}"
          environment-url: ${{ steps.deployment.outputs.environment_url }}
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          state: "failure"

  deploy_to_railway:
    needs: deploy_to_production
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    concurrency: production
    environment: production
    name: Deploy to Railway
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Railway
        run: bash <(curl -fsSL cli.new)

      - name: Deploy to Railway
        run: railway up --service ${{ secrets.RAILWAY_SERVICE_ID }}
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
