name: Deploy to Railway
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

    secrets:
      DATABASE_URL:
        required: true
      NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME:
        required: true
      SECRET_COOKIE_PASSWORD:
        required: true
      STRIPE_SECRET_KEY:
        required: true
      STRIPE_ENDPOINT_SECRET:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      CLOUDINARY_API_KEY:
        required: true
      MJ_APIKEY_PRIVATE:
        required: true
      MJ_APIKEY_PUBLIC:
        required: true
      CAPTCHA_SECRET:
        required: true
      NEXT_PUBLIC_CAPTCHA_SITEKEY:
        required: true

jobs:
  deploy_to_railway:
    runs-on: ubuntu-latest
    concurrency: ${{ inputs.environment }}
    environment: ${{ inputs.environment }}
    name: Deploy to Railway
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Railway
        run: bash <(curl -fsSL cli.new)

      - name: Deploy to Railway
        run: railway up --service ${{ secrets.RAILWAY_SERVICE_ID }}
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
