name: Deploy to Railway
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy_to_railway:
    runs-on: ubuntu-latest
    concurrency: ${{ inputs.environment }}
    environment: ${{ inputs.environment }}
    name: Deploy to Railway
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Railway
        run: bash <(curl -fsSL cli.new)

      - name: Deploy to Railway
        run: railway up --service ${{ secrets.RAILWAY_SERVICE_ID }}
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
